name: "publish library to npmjs"

on: release

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: 20.10.0
                  registry-url: https://registry.npmjs.org
            - name: install packages
              run: npm install
            - name: install packages
              run: npm install
            - name: Build
              run: npm run-script build-library
            - name: publish
              run: npm publish --access public
              working-directory: dist/test-ng-lib
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}