name: "publish library to npmjs"

on:
  release:
    types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          id-token: write
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: 20.10.0
                  registry-url: https://npm.pkg.github.com/
            - name: install packages
              run: npm install
            - name: install packages
              run: npm install
            - name: Build
              run: npm run-script build-library
            - run: |
                echo "@username:registry=https://npm.pkg.github.com" >> .npmrc
                echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> .npmrc
            - name: publish
              run: npm publish --access public
              working-directory: dist/test-ng-lib
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
